/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyFormRouteImport } from './routes/privacy-form'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventSlugRouteImport } from './routes/event.$slug'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyFormRoute = PrivacyFormRouteImport.update({
  id: '/privacy-form',
  path: '/privacy-form',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-form': typeof PrivacyFormRoute
  '/profile': typeof ProfileRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/suporte': typeof SuporteRoute
  '/event/$slug': typeof EventSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-form': typeof PrivacyFormRoute
  '/profile': typeof ProfileRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/suporte': typeof SuporteRoute
  '/event/$slug': typeof EventSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pedidos': typeof PedidosRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-form': typeof PrivacyFormRoute
  '/profile': typeof ProfileRoute
  '/solicitacoes': typeof SolicitacoesRoute
  '/suporte': typeof SuporteRoute
  '/event/$slug': typeof EventSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pedidos'
    | '/privacy'
    | '/privacy-form'
    | '/profile'
    | '/solicitacoes'
    | '/suporte'
    | '/event/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pedidos'
    | '/privacy'
    | '/privacy-form'
    | '/profile'
    | '/solicitacoes'
    | '/suporte'
    | '/event/$slug'
  id:
    | '__root__'
    | '/'
    | '/pedidos'
    | '/privacy'
    | '/privacy-form'
    | '/profile'
    | '/solicitacoes'
    | '/suporte'
    | '/event/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PedidosRoute: typeof PedidosRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyFormRoute: typeof PrivacyFormRoute
  ProfileRoute: typeof ProfileRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
  SuporteRoute: typeof SuporteRoute
  EventSlugRoute: typeof EventSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-form': {
      id: '/privacy-form'
      path: '/privacy-form'
      fullPath: '/privacy-form'
      preLoaderRoute: typeof PrivacyFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PedidosRoute: PedidosRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyFormRoute: PrivacyFormRoute,
  ProfileRoute: ProfileRoute,
  SolicitacoesRoute: SolicitacoesRoute,
  SuporteRoute: SuporteRoute,
  EventSlugRoute: EventSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
